<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script src="/js/dash/tether.min.js"></script>
<script src="/js/dash/bootstrap.min.js"></script>
<script src="/js/dash/jquery.cookie.js"> </script>
<script src="/js/dash/grasp_mobile_progress_circle-1.0.0.min.js"></script>
<script src="/js/dash/jquery.nicescroll.min.js"></script>
<script src="/js/dash/jquery.validate.min.js"></script>
<script src="/js/dash/front.js"></script>
<script src="/js/dash/jquery.dataTables.min.js"></script>
<script src="/js/dash/dataTables.bootstrap4.min.js"></script>